In [ ]:
#Escribir un c√≥digo que lea un JSON desde esta esta web api
#Pasarlo a un DataFrame

In [ ]:
import pandas as pd
import requests
import json

In [ ]:
url ="https://jsonplaceholder.typicode.com/users"

In [ ]:
respuesta=requests.get(url)
respuesta
texto=respuesta.text
texto2=json.loads(texto)
pd.json_normalize(texto2)

   id  ...                            company.bs
0   1  ...           harness real-time e-markets
1   2  ...      synergize scalable supply-chains
2   3  ...       e-enable strategic applications
3   4  ...  transition cutting-edge web services
4   5  ...      revolutionize end-to-end systems
5   6  ...      e-enable innovative applications
6   7  ...         generate enterprise e-tailers
7   8  ...         e-enable extensible e-tailers
8   9  ...      aggregate real-time technologies
9  10  ...              target end-to-end models

[10 rows x 15 columns]

In [ ]:
jsondata = json.loads(texto)
df = pd.DataFrame.from_dict(jsondata)
df.head()

   id  ...                                            company
0   1  ...  {'name': 'Romaguera-Crona', 'catchPhrase': 'Mu...
1   2  ...  {'name': 'Deckow-Crist', 'catchPhrase': 'Proac...
2   3  ...  {'name': 'Romaguera-Jacobson', 'catchPhrase': ...
3   4  ...  {'name': 'Robel-Corkery', 'catchPhrase': 'Mult...
4   5  ...  {'name': 'Keebler LLC', 'catchPhrase': 'User-c...

[5 rows x 8 columns]